version: "3"

services:
  postgres:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: movies_database
    env_file:
      - pg-variables.env
    volumes:
      - ./data:/var/lib/postgresql/data

  service:
    build: ./app
    entrypoint: /opt/app/docker-entrypoint.sh
    depends_on:
      - postgres
    volumes:
      - ./static:/var/www
    expose:
      - "8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@admin.com

  nginx:
    image: nginx:1.23.0
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx:/etc/nginx/conf.d:ro
      - ./log:/var/log/nginx
      - ./static:/var/www
    depends_on:
      - service
    ports:
      - "80:80"

  etl:
    build: ./etl
    environment:
      - POSTGRES_USER=app
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=movies_database
      - FILE_STATE_PATH=./storage/local_state.json
      - ELASTIC_URI=http://es:9200/
    env_file:
      - pg-variables.env
    command: /opt/etl/docker-entrypoint.sh
    volumes:
      - ./etl/storage/:/opt/etl/storage/
    depends_on:
      - es
      - service

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node