FROM python:3.10

WORKDIR /opt/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV UWSGI_PROCESSES 1
ENV UWSGI_THREADS 16
ENV UWSGI_HARAKIRI 240
ENV DJANGO_SETTINGS_MODULE 'config.settings'

COPY requirements.txt requirements.txt
COPY uwsgi/uwsgi.ini uwsgi.ini

RUN  mkdir -p /opt/app/static/ \
     && pip install --upgrade pip \
     && pip install -r requirements.txt

COPY . .

RUN chmod +x /opt/app/docker-entrypoint.sh
RUN chmod +x /opt/app/wait-for-it.sh

EXPOSE 8000
